### PR TITLE
Update localforage-indexes.js

### PR DESCRIPTION
**Pull request by stigmergic**
while setting up testing in an environment that does not support localStorage I discovered an unhandled rejection.  Adding these lines makes the rejection bubble up to my code where I can handle it.

### CODE REVIEW

**Review by tony-blockchain — APPROVED** [review]

**Comment by stigmergic** [comment]
@liqwid do you mind publishing this to npm?

**Comment by liqwid** [comment]
@stigmergic reclaiming my npm account, can take some time

**Comment by liqwid** [comment]
@stigmergic published 1.1.1

**Comment by stigmergic** [comment]
@liqwid thanks,  I appreciate it!

**Pull request merged**
